apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
  namespace: registry
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: registry
spec:
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mariadb:10.5
        imagePullPolicy: IfNotPresent
        name: mysql
        envFrom:
        - secretRef:
            name: mysql-env
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
